pipelines:
  - name: BE-CD-YAML
    group: defaultGroup
    label_template: "${COUNT}"
    materials:
      - git:
          url: https://github.com/Vamsi-PrimeSoft/gocd.git
          branch: main
    stages:
      - name: environment-connectivity-test
        jobs:
          - name: connectivity-test
            resources:
              - jfrog
            tasks:
              - bash:
                  command: cat /etc/os-release
              - bash:
                  command: hostname
