pipelines:
  BE-CD-YAML:
    group: defaultGroup
    materials:
      git:
        url: https://github.com/Vamsi-PrimeSoft/gocd.git
        branch: main
    stages:
      - name: environment-connectivity-test
        jobs:
          - name: connectivity-test
            resources:
              - jfrog
            tasks:
              - exec:
                  command: cat
                  arguments:
                    - /etc/os-release
              - exec:
                  command: hostname
      - name: folder-setup
        jobs:
          - name: create-folders
            resources:
              - ubuntu-agent
            tasks:
              - exec:
                  command: mkdir
                  arguments:
                    - -p
                    - /home/ubuntu/archive
              - exec:
                  command: chown
                  arguments:
                    - ubuntu:ubuntu
                    - /home/ubuntu/archive
              - exec:
                  command: mkdir
                  arguments:
                    - -p
                    - /home/ubuntu/prime-square
              - exec:
                  command: chown
                  arguments:
                    - ubuntu:ubuntu
                    - /home/ubuntu/prime-square
