---
pipelines:
  - name: TestPipeline
    group: TestGroup
    materials:
      - git:
          url: https://github.com/Vamsi-PrimeSoft/gocd.git
          branch: main
    stages:
      - name: simple-stage
        jobs:
          - name: simple-job
            tasks:
              - bash:
                  command: echo "Hello, GoCD!"
