---
pipelines:
  - name: BE-CD-YAML
    group: defaultGroup
    label_template: ${COUNT}
    materials:
      - git:
          url: https://github.com/Vamsi-PrimeSoft/gocd.git
          branch: main
    stages:
      - name: environment-connectivity-test
        jobs:
          - name: connectivity-test
            tasks:
              - bash: cat /etc/os-release
              - bash: hostname
      - name: folder-setup
        jobs:
          - name: create-folders
            tasks:
              - file:
                  path: /home/ubuntu/archive
                  state: directory
                  owner: ubuntu
                  group: ubuntu
              - file:
                  path: /home/ubuntu/prime-square
                  state: directory
                  owner: ubuntu
                  group: ubuntu
              - file:
                  path: /home/ubuntu/rollback
                  state: directory
                  owner: ubuntu
                  group: ubuntu
      - name: check-stop-be-service
        jobs:
          - name: stop-service
            tasks:
              - sudo: systemctl restart apache2.service
              - sudo: systemctl status apache2.service
