pipelines:
  BE-CD-YAML:
    group: defaultGroup
    materials:
      git:
        url: https://github.com/Vamsi-PrimeSoft/gocd.git
        branch: main
    stages:
      - name: setup-and-connectivity-test
        jobs:
          run-commands:
          - name: setup-and-test
            resources:
              - ubuntu-agent
            tasks:
              - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - >
                      cat /etc/os-release && \
                      hostname && \
                      mkdir -p /home/ubuntu/archive /home/ubuntu/prime-square && \
                      chown ubuntu:ubuntu /home/ubuntu/archive /home/ubuntu/prime-square
