pipelines:
 BE-CD-YAML:
    group: defaultGroup
    label_template: ${COUNT}
    materials:
      - git:
          url: https://github.com/Vamsi-PrimeSoft/gocd.git
          branch: main
    stages:
      - name: environment-connectivity-test
        jobs:
          - name: connectivity-test
            resources: jfrog
            tasks:
              - bash: cat /etc/os-release
              - bash: hostname
      - name: folder-setup
        jobs:
          - name: create-folders
            resources: ubuntu-agent
            tasks:
              - file:
                  path: /home/ubuntu/archive
                  state: directory
                  owner: ubuntu
                  group: ubuntu
              - file:
                  path: /home/ubuntu/prime-square
                  state: directory
                  owner: ubuntu
                  group: ubuntu
              - file:
                  path: /home/ubuntu/rollback
                  state: directory
                  owner: ubuntu
                  group: ubuntu
